version: "3"
services:
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mintbankdevelopertest
  app:
    image: developertest
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql